version: '3'

services:
  db:
    image: postgres:latest
    container_name: my-postgres
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: my-redis
    ports:
      - 9999:6379
