version: '3'

services:
  db:
    image: postgres:latest
    container_name: my-postgres
    restart: always
    environment:
      - POSTGRES_USER=linkfriends_local
      - POSTGRES_PASSWORD=Roqkfwk01!
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: my-redis
    ports:
      - 9999:6379
