apiVersion: v1
kind: Service
metadata:
  name: catsnewyear-dev
  labels:
    env: development
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: catsnewyear-dev
    env: development
